---
- hosts: all
  become: yes

  tasks:
    - name: CREATE DOCKER DIRECTORY
      file:
        path: /opt/docker
        state: directory
        mode: '0755'

    - name: COPY DOCKERFILE
      copy:
        src: /path/to/your/Dockerfile
        dest: /opt/docker/Dockerfile
      become: yes
